# .travis.yml file for Travis CI Automated Build configuration
# Version 0.38

language: java

jdk:
  - openjdk7

branches:
  only:
  - java

sudo: required

before_install:
  - sudo apt-get update
  - curl -sL https://deb.nodesource.com/setup | sudo sh

install:
  - sudo apt-get install -y nodejs
  - cd './WebContent'
  - sudo npm install -g bower
  - bower install --config.interactive=false

before_script:
  - cd '..'

script:
  - mvn clean install

deploy:
  provider: s3
  bucket: "com.sungardas.releases"
  endpoint: "s3-us-east-1.amazonaws.com"
  skip_cleanup: true
  region: "us-east-1"
  upload-dir: "travis-builds"
  access_key_id:
    secure: "IQD4XlV8aN6j/Dr2UOLvdzuJhfVDBngkpD4RDe+qGToNfOty97HKAlA7CTnOSaARwZ3IhkQbVju5rEdD0M/r4s9oe4AnDml8WsaMI42V9weziC6t6Or6rP3MHbbwo/apvjtSS3wzQygi/sgqrJrrQkmGq0jYiUU12t/wDq5HpNTdgU//vK0jgnSp2JWanfbVO8Gwe2eBjUvmJoQs5Led4c/p//1rZydC8Gj1QfK/U+16ATFwoDqLRCo2HsHNQCCnjplfIrvd4ILAL/CZ98LI1gyLMeJ2KQy4PwrCHfbCotEHtuT0gSnLZaYqfHTKmaU53R6DbrUxAMsgKm3QFNJWMvI33h61GDVEgoXR6i7Rqp/AX2TTtJNQ0cjl3Nj9TkJUDSLN+4PwGNuBaNlCYLY0WOgGKyPrfAoVrYPoQ3N9L7jpH0UR6gGVcAmI8zU/UlCLgDgn5FRkpEqizScfyxpXn0BBRmb37qZWImkXcMSlM8S2GeOhAPKiH78aLtcM75mQYjLIMpwewj+BcsVz78qyAFORPmw62AwVx2pcY0R1VZk6DdXyvzj+twe3WMSajdYJKMIYhr8N1R3RdIEckcGc3Jtv8sNVrJ5OBD40p45Gy9XPjDZ2iwFw5ppKVVe4QiIJEBCyDP2HsDvtfg+H1ssNw661rt4Hi+m3a1lMEKyVXI0="
  secret_access_key:
    secure: "EhrAOhxkF+8YploFRhhjjomprJ1tjvzLEEtkfUY+EopimParwnWi8ksAknGOWCKwi8G3KuYEBUwge5NZ5kSoUIfba2Xe/xNfKqQK9wr2S8FDFF/SKJCJ0n/+iTtMlR4b+amwpHiK1UNW2bHPoUipU/kgUZt4l2XiDD2JCvgcMPvmLEK7XMeaQeafKWd3r3DOkkuvCB7rjyeg3KyBiOVBwpVD6AQv9NWkHF1aEsOUxtBrSZqKkKvrSNlOx4aPfK5XLM7VsLi+ara77yy7SjRmF4ilo4UdJZaBC1E29JOMA6R4fmxVNlndVq9xDzPFStQHq3UdVh3k+X8MFIAFt5Oz8UaBgH3Ly+Nq/dV3fenQ2Hwlvq5HiiBU4YkHgjI05JHB0Ph33KL7pqrnLpoOKiEM26S4GXpDVpPV0IM8BrlWEM6DJH7rAXIzQMxucf175WdXqVxYBE/4lPFNktIIp1xXXnEgYXCBsEHXQQsqcRRztdg2zdSODWkkToyM6SeCSSh3+oVMvkuE8EwS+90Ik7q5OaFEcPAh+di78bfdHRdkVUkHq6+SKRgPvPEJGwo5upjLl9UuofSFw/O5Zfa5EWLWMrL33hCnkcRYVTVboz/YQbJIcQzqxjCAKQpq4co6byoxIf2W0L15Zt97mmk/sQi/IzMGIA2CvNOsP1Nw5rKIC3Q="
  on:
    branch: java
