# .travis.yml file for Travis CI Automated Build configuration
# Version 0.57 9/14/2015 13:05 PM

language: java

jdk:
  - openjdk7

branches:
  only:
  - java

sudo: required

before_install:
  - sudo apt-get update
  - curl -sL https://deb.nodesource.com/setup | sudo sh

install:
  - sudo apt-get install -y nodejs
  - cd './WebContent'
  - sudo npm install -g bower
  - bower install --config.interactive=false

before_script:
  - cd '..'

script:
  - mvn clean install

before_deploy:
  - mkdir build_artifacts
  - mv -f target/snapdirector*.war build_artifacts/snapdirector_0.0.1_${TRAVIS_BUILD_NUMBER}_${TRAVIS_COMMIT}.war

deploy:
  provider: s3
  bucket: "com.sungardas.releases"
  endpoint: "s3-us-east-1.amazonaws.com"
  skip_cleanup: true
  region: "us-east-1"
  local_dir: build_artifacts
  upload-dir: "travis-builds"
  file: "*.war"
  access_key_id:
    secure:
      f/Ep6w1BuWXbeFlj2QRgUTMt2JpNMQ7DXtZRxhTnfX4UJ8+V8sfvbxphkpV5vgCFfNIbriX3Ht4hf3pXHxyKvmODfm/YvzLGVD+THAreHq43isFNaWGIVR0/pnj3XpwolNspbjkZeSjcMH+DXmpJ23QrIwiVVlyf9YVC2hgKcxAZH0KTRzFgCO3BGLU+PKXKSjbOa9dx1XUpZMovVaFyYT33Ph3ARLvJSE7voshXx3u2QZ7rNAF98mXd3yjIbDF/5aCXDSv9tURNOMY/zxmU4KiPicQ9bVhxOOAwSIagUaueXqX2fX6mYw77+s6ouezgLonYi9VWokr4soYJrHvzcs8RY3+0Qz1QVf5GrSY+TA7RBpnhR10ErIXGZ9acV0C3+1czzkE+kLf73A/rT7C01caIcaaUzWBKfoKRfQiJI2NkQvxmQT801qbuXETXlB/ScfmZmRa2oZuAMuOCR4o608hx4Aa9o1OYtSi01HnabV76TQ19mcHeySmh2eOGJK1dGfTin/sITU+Dj6dW9N6IFV76b3nquU/INKx6y3x6cBiEj4YrB1ySWoE7NPkO85Tmm1OGvONYJDtTzotdQjZoxoVVuilrzTA6iYaf4U6dJm7j6CtLsPH07pasGsqi3VjNpmxB+lOm7H+Cuj4J39qc3tpnrVWM8uzEPkiQaXLv6Kk=
  secret_access_key:
    secure:
      FlKtQzTkLu2CCu7HXuKiAbZxCR15SO00tp2VxTeDUP4z4lsW6a8E8RQSWS8dZTUogMOHz0FgKRD56O6Hw5rywI1nmwF8FvNY9aNQFhPfSYFbxqcuscI1E9uj1UEwhAWyingocQdTgSV5123rzhlqSF5VQ+0ddPj0l2kL2lkeGDZDzcVjDDiW7M0eVOD6NF4LsDCjG1O/7GiI+uk7zzn1s2cQwOdcPM1Y/nD7gUOwz94YXLnNbortdcerZ8eby/4H7bsnDWwQ/8yHh88M/ketzrPF62KkA3NMmtwQZ5BLKPCGHw50Pk890RsG4bOTeixDFxIOcUdmp1TUmyoutDp8g58T+EVJakHROcWz1Brme2OVUldCg+tDMhhCr1IQ7r/+IOyzDsT1z64Y/JgfoJkzz0zm4O6pN5WIeqHupn3H5IFERbz2yIHby1zvzmWO9k8prKZmMRZ+0tPQS3lHc3bbTXswia8vlBMyF36nsYKgp+k6utag9NQ5DG/pQsQtNt2TjD9Ux3FJLzTTCvHPHnd4rygAW9/CMlaxEeUzSYWNGgIgGUXxR9lLFpdbaS9bcExD8ovH6rz4hQU68ilTxx8dGny9IO+Q3Wu8u3EH+/JFOx9ErqKNvCIw7fv9kO0DubW15Oaqz8uD4eOxooEdrMegfE+ZN0YpJmoqqwU2iNZ0RkQ=
  on:
    branch: java

notifications:
  email:
    recipients:
      - secure: "OVc4HpmwgFIWfhv1Lu3hbMByj1p5r0p2lt4vzTgPLCVt/OQEB1tzFdoW4jROUJssLRaH3rLGLGOjbtBOjEV4uXZzeXWo3J/e5qKkNzOrjnzuPgg5GxpUIiMSbYGn0mtufrKtf7vIWGZFuFrq2LrB/FgcppmBl2/zOGgXi9xU9abylqA1K/PPg9oZfzznCBD8GW/7GLOv3FamUj9RjdruWfDT93YwZ6MZ8urVe95gt37I8enR40hnUDcHtRiDZxH40cUzrDm8nzRDdRCOBpSMWiBv2CTML+2otVsBbXAx0n/lxnb86qWLLV+z712PAwl5crunJqNanbeWx0ZOJyQxIEcGlVKC8NcSKyqKOJGz372VRdcWFak+e/4bunceEwDBQWlWD5VgAR1IwK9xDMHQt6NVxV9aC8xiehph4Fa3XfEhpIZBa/TGw8YSFvdsvldR+gTbqetYm8uAoKOxKFLy5KJtXfv4b6fxilTZVp++Soq4idiXUJLvBQAxdarvh6PuNA7Dk58XH4o/cdVmZyvt4qNmWMyp2D+VEIb5AQH/2l2MmTmFCrMfnFWJ6qACq6T6mPQ9UsX7XMZM5jhsCpNoJVL7b+jz9jLLkiEkW/x7ZI4I78XCw02LRV2leoqYhQ1A5Boe0LJRDGuAxF8UKdHNcjVaIuqi8DPUoltkBYkoptY="
      - secure: "cHxfyyfe/O+gLHYfT6nu68VZu0/FEECobMyRoKoIth7M3ePaudDaMXxPVXAxy/lhg2ivl6H7eBYt/DnJ+8XhrW8Gzuk/WoOCyegin+LA7VHbHBpz16o303dPKU6La7LwIE6JnVo/DSzQQp+97gwTnAO05DKDqzKiNVxlAVFKFM61vRg5zsnxAzeLjnMGaMiAAiu/sHI8nzmMG9m8qXEJItgNKBtSzjGbTgya6Hc3YKoM3ghjLqUeTxYJR3tWnn27VB/ikKhrRQLx2CdM2y2Tg8l51cxDdiFzCU2xlp4lgCNxUVt6xY6E2jiM7Vg/tHfRATDUqFj1ULHhFKuv9nLmCjE4sHlJJJYLKWyV7IfwVNRNrqktzm/3M+j1H6r+bbk0AtQ9LPsHVJ6fyumNdCvHFEevzl7oieF3rvlKD32yYJ20AyMHhkN0zMX/q/0rOWRnXpsiYP7tfIA9mqWO+3rTJMTly2YPhPzTMr/5y9VEGpISNFH1cU2OKCbbp7yd3ONvCNLYiZR/44iEzkaGviDZjPuZVaIi7EB1/Te9SHgtAuoJXhAWIi0+kfKiycgimty8gX/5L4hwq+Z13Gx17VvgEqZUaZsSSaD6QA82YnRCfzSp+PZLvkKOR49P+DoDT2UqBd3F5gW+5hZrCyiNAyJ7/6b0kZbpsg1tIyjGSERufxE="
    on_success: always
    on_failure: always
