# .travis.yml file for Travis CI Automated Build configuration
# Version 0.25

language: java

jdk:
  - openjdk7

branches:
  only:
  - java

sudo: required

before_install:
  - sudo apt-get update
  - curl -sL https://deb.nodesource.com/setup | sudo sh

install:
  - sudo apt-get install -y nodejs
  - cd './WebContent'
  - sudo npm install -g bower
  - bower install --config.interactive=false

before_script:
  - cd '..'

script:
  - mvn clean install

deploy:
  provider: s3
  skip_cleanup: true
  acl: public_read_write
  region: us-east-1
  access_key_id:
    secure: cBLoHwmOA5wUfuH7FC4jFMIq4+/RREj9rJjoD2YyI9qJJ5Nfj02mAW/urZIEUG26EStXqTic6HTI+4taSTVcBCTj+Mu7e7GpHSD45roOSomOAUD0UeYvKYPbWQkpvKGAGKtHjo/IQRutXRdjdi5PGnySM+ld9fTG7yKA5vqZbLQP+huKAw23TRl9sS1J1y0ggoGrAk5uOg3KLF8SogTtwo/mdmqeVa1swjnJmgzdWPWQlmbWD58hEaYCJPjS/awmgnJdY4vXhKcJ70c9mypenQ122hpP4v/ysvui7xc/YmnPvF2e1YXfEaUP+o47GzJgrW9hX25XZbuYzPl+X1zFWHw7YHbRY540VZ2QZUZH2MZlWYKLr4zchbbwOkLL6rDxC/1OYIsP1iUXLyhHHoLCKw4/jq4ekJwA9HQ0ZJgJjWkl7fEDvqXLyEPU4I4nstFfAytV+sv6RFzsO1rfsvY9yUAq6VOiAPK6Q7Oa1h/yHQWNgdtOG3ZxxSjgxh4I9rfSnsLGu45dUddBxPS/XIkUUdpM3gbDYdf+/+wsUnEgUsPwmc4tPMiM6CUjvXRyVp3/mkrQ/AJOWnx/lgTs4vykVbA3xXI4IAjV0gcsjtT+hKiHRn9jTJ1sFbLrQ8sAark5Hp1KUcWnnnN61lXdjnqRhw+sYOpeLEVXhIdG+OYvOS8=
  secret_access_key:
    secure: Ykfgf+R2M+2jqhNLMLaDigA+Z+t6Vhrotqspjv3TW+OvjvQvABVX0hWcT2kP+QFNG622kouNl3yKyMEZ86+tflrnWIcGDLZLcrhgBx2miLzgzCkeV5KtUbIxuKZgO8QazJDqZ4j2xYeonIId51cgr8b5njMsQW1rI9qIRhvYmZCrmeBpvTT7xHQmsdcEeDAG5uvPsDfMUIpRo5OuCY51gbB6Hkd+HX/J8RUiN0a9xM2zjnOJ7H6EWdWeYVnpOqzReLv1JGheo+qT8ndOP5Mn9sWVVGMtQ0MurAfQdvowlx8jGUfch7g4HlWz8y8/mgxhynnZrTJSs6CVFUEnjcKkpx4Syv6W7CmH6EX3BH0/+DJ6gPoBo5Xbq+MaowhYw5as7ZmDjPkCKFvf+dZsF3ybToPDY8ldW/5fuZ1PTeMF+jQtlgdx3s9JO2mi25oWSYlaUYzUNwXMVdi4OV3OJ9979nGVAJaCJ+pSv1XKoRAXd2KD0SrCg24I71dLzsFNhApIUGzdKBNMmUoKIHWjN9VB+ubzWoF0RY26aJL5rsFH10x92Wy3WSgLnyTndqMqlnHI4xu670acmfSOj76Yb/B2EjDH0t1mnGEk4DGBngST9kpGSD1Kjy+8mXTg9h3SFsrxtko7oQTYGrxqCWQj15QvItMMm1A8m7BwsRZzELV0YkI=
  endpoint:
    secure: BIHtGEbezpgE5ik8lW26qBsTnGS0Au7n6TLmhvIAbJERiiTvqzMg458yRka11houavQIn/lC4h+VkkRt84YbLVyQbk7KFS7P9YhQWADFK5uTk+/+rmT152Eg6biOkfo+E1Chp360ZEl5URyp/i+9vc0CAHVcozx+3/Uqoga21RQrWiVKgrg7LyC1xyQMkLWHI3Mr5+NlZlYbQalbI/6TlhkyTPsN+zkE5HBAA6BtOQXycVxGz5ZAaQbU0JZskjN+XqTEwHN95V64/zc9c7xDJFMDK4B0UWbt160g9dj2WU5VqDIhQ7YX/4NdaYOsjkgpX/d05h9xJzsx2UPXea0hUw+cLg2JTwy2HTGOcexm8sU/AevtZzWTpfU2OnLoZg+vcQwFxVd5ngn3+vMLSb+iRccjssWV4F3TqwGZeLkdccfpbrpl2m8WIht/hnXbLLKFJFx+k5IUbfOoy0AncZyoEl7xwpkVsmFntxzmoeZ/OBqBXONXd0gTWvJWa4l6bMSEA+KC8uAAggnEzy23GhAKgm2rzzIYFcM7FqwMweWd4tzEsz9FwtXxoA/sAQDXsk6pj8O73FFfMEpsKr5q0GJZUfhyyI1BvvkmtAMLkqwuyuqbGb1n5qMXP71anD+fvlgXDLKDyH7fzOwFfzaW8jticgqByPtPoI7dZkbfDBA/gOc=
  bucket:
    secure: TG493s3AwD4Rya5ht+ej27OQSj425Lct9BZZhLlgpFWbYF3R7IA8purs/uo4WoNKeIdSJy+Z7qDGa/bvN4gf3TyTSOdfyb+bvTwcrjryjuR48Zeil3Uvp2Znj/OC0wqbo9v/YrwGWKgk9cXnnNbX7QSZzMkqyEAOzdaCuM8oKi31kVXtogAhxZxWSJThFKv88pxnMIoU1M+NRHfVJG83xsuzBD8KymPMkublWUrns8jAm5SgYEhMdfq8mbO3v7NvGOpTLUoKA9+cvyDTJTRunWARAbL+mYzrbXcmDm9iPUAFlitpFUfej7gF6hl2qwbe8F7Y+7IHDdcxS1yT/j9OEMbBqwCHVb+DkJE7ZWzKaxA3Ogjcn2o4SiPnBeguZ62IC86c0zvuvOF8Gb5m1CftO0USCipRZBMOBhUYx+wzA3Ri2taKerAE+wkQMLPNN/uJiiiK3zHlDTI3O6catQkdVyRHZmQjViwVzK2BBqZGSThHEacoiLGIZnYXVsjNiIocqn/ZOjDSCmg2jTlR0Liumnff2dFEDnYR2uZ9bFUSKUgSplNitQaMH9/v/mHjVHa5iUzhhZOu1fgbFxTmqfAYrTORCnLrWHhI/c+NX9jOVWp1+K4mcKpv0yL9RV9ZunC3p1xk6/7DCfaN6FXj+klboxufiKC38uW+wkuNE6XopPA=
  on:
    repo: SungardAS/snapdirector
    branch: java