# .travis.yml file for Travis CI Automated Build configuration
# Version 0.30

language: java

jdk:
  - openjdk7

branches:
  only:
  - java

sudo: required

before_install:
  - sudo apt-get update
  - curl -sL https://deb.nodesource.com/setup | sudo sh

install:
  - sudo apt-get install -y nodejs
  - cd './WebContent'
  - sudo npm install -g bower
  - bower install --config.interactive=false

before_script:
  - cd '..'

script:
  - mvn clean install

deploy:
  provider: s3
  skip_cleanup: true
  acl: public_read_write
  region: us-east-1
  access_key_id:
    secure: "bimIQgLVLgNWTqjcUxLvUgDDOpJ8aGLqYZ66z8A3c7EIrWzjx9drGIN6z/pl26NQZPYG8XxS6AtoHRnvrxN0QOqAdctiy1R1PSv+HNuCGPQ3BZc1idngC55bqlKpMWW406qEB5QpQYqKqZGdfMiABzxCZcVj3yMagJLIqOVwg8TbuB5/UuDWEbdx2L3o/kVmIYJXborw77tZSznkes5/980WVJYyJRSG94tCsNifVecP3CCod5yaoG5Z6layIoGSsEGctQHbmrdHkOwxaMNKssPbhBIfprgCYMfdw/kvDphqxc1eZLlOyF1WVFjuuWfSWEe+uGTMpRXizsYLhRi2DrWqd5wH2d2/5e4evo8LD2/3sIHn1J4EHbYAfz6cMEswa7hSDNgH+0nZ2xVlPDJBcOlZLYIwfzHeUa5vYniOe3BwxD+iD6B4Wv8nNiiNsJ7PTId9Yt8BeAOgpkvjj62hd0nU2bu2lrVMjFkXLNY+hio06mvRh5cZ9/830jEsZbzCQimemFTj6BEvZfDNdeldxopKyKL0ktGFsgh6EJgDzDmyILsr0k8Qy/scciaESEsAoXLCOgx4+1ovQVfoMwMuxoSSg2TIsQXH5w1/ZqElNYIfXFTY40aFto28RQJi5HMCgHkkcBJdbWkr/O3BDsju2MGQqCAv8ywniQZvYDfWG2Q="
  secret_access_key:
    secure: "RGtFEgAUTlRD8vCbIJ1/Jdu3d+D56LagKGm9Tb+8xMEwTNOzNqPQNFVkckHGOBL7xaTv0blY12o41nWO/U0gmiMrEbysGCEzSFdhS6dTsynWgLgHOr0GNZONFnV6cEom50WvmI8SI9trv4H/S57W6HLlXmAKjbBnhsT/bQubaBGvizB1JcW+3pbFA6YWXWticJ35fGlyrW+0bgr/gZLk5MDARIVo3LiOkwdT/i7jES/UdELme997xCKE9jOYRxEubYig2JouOl0DOW9H0SbdRgVrB6GrDzkY4Rf094WnZt6bVceSvDxYv/B2pWK4jfvVe6RimKxlsYH6kiILfnWHWqCC5NI8cWVUatjc/59obCdGCmbH0w1hjSsRVmCF2kSLho5RxibBq87t2G9/CvJXgpglafs2CISMxxJ0xHbSfVmj9tJHGM0/jaYu8yazmPunj02R7IX8YpsbuUxcOFcZ7DT3r612U1v9LUL+ob97ya/6FV2TrWg79Muz1hC6hwNclXpaIhwzbMCV1gx7wK6WYRDsPGCBhGtPkJOhOWMLCykjSPDiLOo5eqTUjnUK6R3TEAiSnRwpr1JSIEfuO0YEzyzvkUPR5VDXaK7Zs+4/K4cif9KBT8bdSOFIb46b9aBPJZSjQnW0T4pRhkzNO3wAhBA3SnG2hGnxMhtVQaMOFqg="
  endpoint:
    secure: "BIHtGEbezpgE5ik8lW26qBsTnGS0Au7n6TLmhvIAbJERiiTvqzMg458yRka11houavQIn/lC4h+VkkRt84YbLVyQbk7KFS7P9YhQWADFK5uTk+/+rmT152Eg6biOkfo+E1Chp360ZEl5URyp/i+9vc0CAHVcozx+3/Uqoga21RQrWiVKgrg7LyC1xyQMkLWHI3Mr5+NlZlYbQalbI/6TlhkyTPsN+zkE5HBAA6BtOQXycVxGz5ZAaQbU0JZskjN+XqTEwHN95V64/zc9c7xDJFMDK4B0UWbt160g9dj2WU5VqDIhQ7YX/4NdaYOsjkgpX/d05h9xJzsx2UPXea0hUw+cLg2JTwy2HTGOcexm8sU/AevtZzWTpfU2OnLoZg+vcQwFxVd5ngn3+vMLSb+iRccjssWV4F3TqwGZeLkdccfpbrpl2m8WIht/hnXbLLKFJFx+k5IUbfOoy0AncZyoEl7xwpkVsmFntxzmoeZ/OBqBXONXd0gTWvJWa4l6bMSEA+KC8uAAggnEzy23GhAKgm2rzzIYFcM7FqwMweWd4tzEsz9FwtXxoA/sAQDXsk6pj8O73FFfMEpsKr5q0GJZUfhyyI1BvvkmtAMLkqwuyuqbGb1n5qMXP71anD+fvlgXDLKDyH7fzOwFfzaW8jticgqByPtPoI7dZkbfDBA/gOc="
  bucket:
    secure: "TG493s3AwD4Rya5ht+ej27OQSj425Lct9BZZhLlgpFWbYF3R7IA8purs/uo4WoNKeIdSJy+Z7qDGa/bvN4gf3TyTSOdfyb+bvTwcrjryjuR48Zeil3Uvp2Znj/OC0wqbo9v/YrwGWKgk9cXnnNbX7QSZzMkqyEAOzdaCuM8oKi31kVXtogAhxZxWSJThFKv88pxnMIoU1M+NRHfVJG83xsuzBD8KymPMkublWUrns8jAm5SgYEhMdfq8mbO3v7NvGOpTLUoKA9+cvyDTJTRunWARAbL+mYzrbXcmDm9iPUAFlitpFUfej7gF6hl2qwbe8F7Y+7IHDdcxS1yT/j9OEMbBqwCHVb+DkJE7ZWzKaxA3Ogjcn2o4SiPnBeguZ62IC86c0zvuvOF8Gb5m1CftO0USCipRZBMOBhUYx+wzA3Ri2taKerAE+wkQMLPNN/uJiiiK3zHlDTI3O6catQkdVyRHZmQjViwVzK2BBqZGSThHEacoiLGIZnYXVsjNiIocqn/ZOjDSCmg2jTlR0Liumnff2dFEDnYR2uZ9bFUSKUgSplNitQaMH9/v/mHjVHa5iUzhhZOu1fgbFxTmqfAYrTORCnLrWHhI/c+NX9jOVWp1+K4mcKpv0yL9RV9ZunC3p1xk6/7DCfaN6FXj+klboxufiKC38uW+wkuNE6XopPA="
  on:
    upload-dir: travis-builds
    branch: java
