# .travis.yml file for Travis CI Automated Build configuration
# Version 0.32

language: java

jdk:
  - openjdk7

branches:
  only:
  - java

sudo: required

before_install:
  - sudo apt-get update
  - curl -sL https://deb.nodesource.com/setup | sudo sh

install:
  - sudo apt-get install -y nodejs
  - cd './WebContent'
  - sudo npm install -g bower
  - bower install --config.interactive=false

before_script:
  - cd '..'

script:
  - mvn clean install

deploy:
  provider: s3
  skip_cleanup: true
  acl: public_read_write
  region: us-east-1
  access_key_id:
    secure: "nU4//jueP4gkzXNFoYF+0BVon5lai9kTV5kLq25m1PXemzjoqyZRvhPCgEc6OLXGmpZ+6NztByBZEjrV0sqEAotv/gKpWgvp98GPD3F8t+bDDT5R4Cjt/eeSXVhpwjYhlIEn8jlk9+wFpqU9u6MeqQsz6WipuvSiqCrmGd67r9kHfeZQdO82qBhqyT43/QFQE+DFW0NB97oKoBO98n/r98ERJ10BGGRtIW8tN6qmZE/2C7lmrKBgwuCf6MkC1iBEq7YI9fGwu7XnaqrmBxkBWBBbWhciKpbscA6DNZQoJTtnuEWdv0B4SabaE8VtRqn0gqNhfzJYkiiVJfOUmf/qGednZaoYv5OawMeR4rpsV8T2tcJb5QA7SiuS55Y8UDB+LFK1o/2zJUoevl2dvS3+9ZC9FWD6tCNW2qBKv0OKwax1iA5B7cY6CGumnCTaopZJSNQOgsgKeCKRvKgL6HrhyftqcJ11G5gEuxTYtfzXgKqdqASeVY5Z93gPiOKv5kvoZMhZ9VH6zWxUSBBznCXWrGTZwT1LKi3E8yBHIRQH87qi41RyE+msyW06AsI+R0ijrYDiv/BD4xEKv5iCz3agVx6KzwqcfnGC6CNVi0ZyfqGf9LoXf7prUb0llsIxA45DCWGE9e8w7UEOPSXCoVeybL2Jo1h22uSzIKzjmIYdiqo="
  secret_access_key:
    secure: "G4zUqmzJKPZyQ8iN3MyWbnCQHnrHy+VZ7wE0JsBMUINBQo/ytoZvybvrzZi3U628pbLNyNa4BmsT9MziMF8mAUf1OGsM4AtwMgSaxukLh6Hex1tiXH5+6IkIe7nRdvdw54/V4fKsD+l520lN+qRZ58VHMhfy7d1k+2VK8eUARGS/IIR0Q5sTpLkpsWcAGS8RCujCrMoRm8cGrzPlm/DhJSrWOxDwpbEsaEBrn9hkN2/lIJJN83qM0P+IAIH72xi48NCFCwsR3TFrVy9zoWpUd938UlAae+0YJDASIuE1YZSQHx2k5TMV1VfWvvBY0WqlS66fXB+W1t6o8dmSwb2HkDK+MbXh+toc9h9GL7aN363F5pB0G7aLA7Y7vpTR0H+aV8FZXcQioSdrvbnJU6iskY+SDl/rkSEPk4edIWWTM/7n62pegWmWbXMsMWOrEEN1vZKfmoamRvbtao1FB+X7uVKt3R6SX7RqDw7BgGGdH7x8zEEwa+HyQi0xLw1uy+4uL95t+u3QQg9JaeXfLPxy6GHYBppccyn8doZ83874e0z/ytxgH+tF9gkcJE7hga2G6Tsb0G9vm47ONs+8sGJ/ymJm9iX0NJA1zV9zFU3wIo1DZuBej1GPF3CrIKwIqRJKRbxQp2HUQgzzXjoDSAAgVAkQub1H7MAYW/IL1mRgljc="
  endpoint:
    secure: "BIHtGEbezpgE5ik8lW26qBsTnGS0Au7n6TLmhvIAbJERiiTvqzMg458yRka11houavQIn/lC4h+VkkRt84YbLVyQbk7KFS7P9YhQWADFK5uTk+/+rmT152Eg6biOkfo+E1Chp360ZEl5URyp/i+9vc0CAHVcozx+3/Uqoga21RQrWiVKgrg7LyC1xyQMkLWHI3Mr5+NlZlYbQalbI/6TlhkyTPsN+zkE5HBAA6BtOQXycVxGz5ZAaQbU0JZskjN+XqTEwHN95V64/zc9c7xDJFMDK4B0UWbt160g9dj2WU5VqDIhQ7YX/4NdaYOsjkgpX/d05h9xJzsx2UPXea0hUw+cLg2JTwy2HTGOcexm8sU/AevtZzWTpfU2OnLoZg+vcQwFxVd5ngn3+vMLSb+iRccjssWV4F3TqwGZeLkdccfpbrpl2m8WIht/hnXbLLKFJFx+k5IUbfOoy0AncZyoEl7xwpkVsmFntxzmoeZ/OBqBXONXd0gTWvJWa4l6bMSEA+KC8uAAggnEzy23GhAKgm2rzzIYFcM7FqwMweWd4tzEsz9FwtXxoA/sAQDXsk6pj8O73FFfMEpsKr5q0GJZUfhyyI1BvvkmtAMLkqwuyuqbGb1n5qMXP71anD+fvlgXDLKDyH7fzOwFfzaW8jticgqByPtPoI7dZkbfDBA/gOc="
  bucket:
    secure: "TG493s3AwD4Rya5ht+ej27OQSj425Lct9BZZhLlgpFWbYF3R7IA8purs/uo4WoNKeIdSJy+Z7qDGa/bvN4gf3TyTSOdfyb+bvTwcrjryjuR48Zeil3Uvp2Znj/OC0wqbo9v/YrwGWKgk9cXnnNbX7QSZzMkqyEAOzdaCuM8oKi31kVXtogAhxZxWSJThFKv88pxnMIoU1M+NRHfVJG83xsuzBD8KymPMkublWUrns8jAm5SgYEhMdfq8mbO3v7NvGOpTLUoKA9+cvyDTJTRunWARAbL+mYzrbXcmDm9iPUAFlitpFUfej7gF6hl2qwbe8F7Y+7IHDdcxS1yT/j9OEMbBqwCHVb+DkJE7ZWzKaxA3Ogjcn2o4SiPnBeguZ62IC86c0zvuvOF8Gb5m1CftO0USCipRZBMOBhUYx+wzA3Ri2taKerAE+wkQMLPNN/uJiiiK3zHlDTI3O6catQkdVyRHZmQjViwVzK2BBqZGSThHEacoiLGIZnYXVsjNiIocqn/ZOjDSCmg2jTlR0Liumnff2dFEDnYR2uZ9bFUSKUgSplNitQaMH9/v/mHjVHa5iUzhhZOu1fgbFxTmqfAYrTORCnLrWHhI/c+NX9jOVWp1+K4mcKpv0yL9RV9ZunC3p1xk6/7DCfaN6FXj+klboxufiKC38uW+wkuNE6XopPA="
  on:
    upload-dir: travis-builds
    branch: java