# .travis.yml file for Travis CI Automated Build configuration
# Version 0.22

language: java
jdk:
- openjdk7

branches:
  only:
  - java

sudo: required

before_install:
  - sudo apt-get update
  - curl -sL https://deb.nodesource.com/setup | sudo sh
  - sudo apt-get install -y nodejs
  - cd './WebContent'
  - sudo npm install -g bower
  - bower install --config.interactive=false
  - cd '..'

install:
  - mvn clean install

deploy:
  provider: s3
  skip_cleanup: true
  acl: public_read_write
  region: "us-east-1"
  on:
   branch: java
  
env:
  global:
  - secure: bquUsWTGWSlN2LUeDHJyicE9aAxvF+lnS/S073yy7nh0ghqLdGxOxVBuMKYKaSHedB/dCgD0Ao3GEXE7N5g/NAXXIr8m+u1EgWEptJuX1xV2L9v6qRx+n+sa71wnVcAyb+bWpddnpEWtJLlSvcr3mwZkb2B5pEan3t/FITh4fVzTvy8cn3vxrpBiaUxEX6ctvoLAfo++DARYuxzmKR0MPvnFSuZp16lVdxzUv5Kh8ihaik8wE2pGH+HALHucmkYTUfzRmxgOri3i0U413yDxOUeP81Pt489z9wfxOPV9EZ7FwoBjj7qfmlrltzsnVTWPf+J4hptne9tuzrdB1nAKFy3OSFk15wL/1JolhFauyoE4vseaXiSNZHFbqQBcshwOb8R+aWDPLY+K5bnCP4BBM0J0YA6JXbVkpGjhLkxgnZp355CfYLJZVgfvUV5uUh6wHeAxICGS3RBvwy1xygyLCDzoPl6xo+bEe2sL3kEmYigBQa/5OvSps5LhJ3hmg0HLPUaSp45kB0GXFqu+9JZZvg8cMmjd5Jw5HrRb2O5aCKU+V+dtU6dxyXyYQMoZa/OfxgEnL8tlQqyIXFXj8SdgtXOAhQ6MzUbXmHpPhRfGakDhJmMR3wzNEbi6AVz3vqx1hM0OUv9nHUAhp/1XWtAOMHjmxmENEYj6lfwoqFmf6kE=
  - secure: hdu3gbfmOGXMbMtCdwvmPs9w2PnJbJoQEe9lRsehuYLudIcE4uNxTEihjxEf8ZLk9pK8CfmjczxIWtDvhn6roTxTtyTNHGHf13tyxl2AyafeSK9FfZJyFFR0QKldLrjuIjfzePY+Ga8BFQqtdIr2nylxdCwWsWdnGvjZw1a0a4KPW3bITEJril8GuN4B2xK5hmDXskKaL9/zCjuq2k/yFkjvmxcPTaijO4ZWrpfh6zWuAKFa2xhGcgzVww5bAD7OpbpycIagPWNilryOoIohqo0EZAXvU9Y/2Dk9l0onVosyIsWBpQSM9yZuzYGM/FKHoSmXitM3HqKzkcfdvhsnF55QZYutSmZwo8aMjE+DbXq9MUHOjNV08t2eIzXoC07fWfL1ZvaN+uGOV2ew6AG8ZqW0oiIU+pStCJy+ugsP6OMrqo710IBN1MeP+U2UNwanrJX9Rq1MAraPJURDHXohBEaAoDPTn1fXbl0lcT8yeanFwuiJyUyZB8edV2vJfPt/L40uoJnVeTaOvDf12Y9qv6+lbL+C1tDwoaLwzeLFGF+ZD6gsJBpiT9F9cIvP+Z4IPIG9f9LurZjf2iDCa6WleDUtwxiqmVfYAN6Ye8/MnuoYa85cBWWMZVFtLllnqCi8Pbxg5gOfuWHQGUoZ8KgIYRK9yV2CeRsWAsRtdHvRkNc=
  - secure: EQpIHEaRibyx5bBzF3pNPvsvULafgUvGZ0pFpDv6T1Ffo5uYyNigIqYPrQDb8J/oRE8KWSqKAlhxUvDp96QAeRAp3i3R8jexqh4HtdUhVW9zCUc9ARPRmorw5gx+YoN67s+AsLdwpekKDVtNADknWPQnVhnZu48eq1Z8kY4WP761EcjVGkVv7aYGPhlgLqX9wkvlpMJfnuyca2gr8r7JtrzpdlAg+PGpIgFnm58GgX0DKYvgKKnT/bso9wFelCL1Eo7q2sfmw0wvzQgZB/m+kqFWrhjwVPGnbjG8Fu7c9v+1PZ6gL+LbB9oQOFfYcNLuPt0CFa/zKEpRc891bGbv+m970plhouBqkDIpOsNGOCDiYQLkAh2eNEl2Ty/smSOrrslSMIXktba1eXlJiiTCy4YBImbt5x7sbm6s0LgOfySB7O+LqoF5d9H5lJJM/8FRDb1rAHmBy+WqnkRVxizkZGCJGIRiWRkIeJoWb38E3prknvGkorpnf/2veI3fj+UTLufq+Hj4pizrxWVD60VI+BEGBIBzOorjdBBciUjZgdSc910qoJcV74aBYclf8jEAAUzD3YviFmzmh5XRA9ljMO+S9Rsau4y+m1Ur7YJM3GF7XZTY+wQbc/Xvr+vhnW7Oxi0CTNXfY1xDbvekpjmZYyTWV/GsuAQzbcyE4NfUZ0E=
  - secure: aCim1L7vosF5ZwEAnoTGvCcl7iOjEpyT/yHAJUYuOSmJgQMWE+QcCYLNOb6uwXzJXiidGDsrQHLi6n9JNh1UU9b97q3lFKt5pKF405uFye7yljha+wFknwnx6zr9MEMt2mFLyWugvsZXkjNEBoU1ak9uVfmCoBJgukVprk6rbC6l+Nll7g9yL634DI48+TtUtRFKDytPJ+C2sxRMfNy1gbYr9wLdY04S1mvfIkzKy2fwwgL56MrLrS8/nbgVEEdS1y9VquWnJZBh1aimhVmpbF25ncv1uf6KGtR7+1SgiHxBLdWM56xY5QCJApponxgJiwrwRu6cT0b252yQWRRa7bBNez0F7Qks/q82S0BuYiOAz4K6M8MY49keSZbmpGin+pRpQlpT/wr6MeV2Mduhl2yturDGj3fG8m3Ygf9kp3esBAErvEVgmgwBDzkNFsv0SGBAHz7cHLTV1U52bH3r1+3D1GeJGDjjayCUoD/SCh12PlWjIqe9LSyrfBPYrHrUcMy4jaRg7fI5k8q+cwOnEUXEqF7T4jutJ0CthdbgYHbULMB9gJH8nVjXkp2cbUtDJ79AeycD9OgThg0xrqQ+AOw5JvFirYyEcHuiDwERc30qqDYPHU3/e5CbbaumXXx0YT98v2a35tX0ev4wcKfCya7agdAZnY9EobS6zCcFDWA=
